### ISSUE TITLE
Error code when trying to shrink images

### ISSUE THREAD

**Issue by AnKingMed** [AnKingMed/editor-image-size#5]
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.14.1 PyQt 5.14.1
Platform: Mac 12.6
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-10-20 21:32:43
Add-ons possibly involved: ⁨Shrink Image Size In Editor⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.taskman", line 122, in _on_closures_pending
  File "aqt.taskman", line 71, in <lambda>
  File "aqt.taskman", line 90, in wrapped_done
  File "/Users/Nick/Library/Application Support/Anki2/addons21/1633333766/browser.py", line 45, in on_done
    future.result()
  File "concurrent.futures._base", line 438, in result
  File "concurrent.futures._base", line 390, in __get_result
  File "concurrent.futures.thread", line 52, in run
  File "/Users/Nick/Library/Application Support/Anki2/addons21/1633333766/browser.py", line 51, in <lambda>
    task=lambda: change_image_size_in_notes(browser.selected_notes(), shrink),
  File "/Users/Nick/Library/Application Support/Anki2/addons21/1633333766/browser.py", line 82, in change_image_size_in_notes
    shrink_images(note)
  File "/Users/Nick/Library/Application Support/Anki2/addons21/1633333766/utils.py", line 21, in shrink_images
    note.fields[ord] = with_shrunken_images(field)
  File "/Users/Nick/Library/Application Support/Anki2/addons21/1633333766/utils.py", line 33, in with_shrunken_images
    for m in reversed(img_tag_matches_in_html(result, img_file_names)):
  File "/Users/Nick/Library/Application Support/Anki2/addons21/1633333766/utils.py", line 75, in img_tag_matches_in_html
    IMG_RE.format(file_names_re="|".join(map(re.escape, img_file_names))),
  File "re", line 277, in escape
TypeError: decoding to str: need a bytes-like object, NoneType found

**Comment by AnKingMed** [comment]
It looks like for the most part the images shrunk, but I got this error at the end. @RisingOrange I don't know that it's super pressing given that this will hopefully be integrated into 2.1.55
